# Site settings
title: 127.0.0.1
email: avanzini.arianna@gmail.com
alternate_website: "http://ari-ava.blogspot.it/"
description: > # this means to ignore newlines until "baseurl:"
  This blog is powered by <a href=http://jekyllrb.com/>jekyll</a>.<br>Blog posts
  are released under <a href=http://creativecommons.org/licenses/by-nc-sa/4.0/>
  CC BY-NC-SA</a>, while jekyll is subject to the <a href=https://github.com/jekyll/jekyll/blob/master/LICENSE>
  MIT license</a>.<br>
  <img src=http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png> <font color=white>-</font>
  <!-- hitwebcounter Code START -->
  <a href=http://www.hitwebcounter.com/how-to/how-to-what-is-free-blog-counter.php target=_blank>
  <img src=http://hitwebcounter.com/counter/counter.php?page=5873318&style=0007&nbdigits=9&type=page&initCount=0 border=0 >
  </a><br/>
intro: >
  Hi! Welcome to my website!
  <br>
  I'm Arianna Avanzini and I'm a computer engineer. I have a relationship of love and hate with software bugs, and I do enjoy
  hunting them in both userspace and kernelspace projects. I am an amateur and an enthusiast in operating systems (especially <a href=https://www.kernel.org/>Linux</a>),
  although I love coding at whatever layer. I recently had a crush on virtualization, and since then I have been studying and playing with the <a href=http://www.xenproject.org/>Xen</a> hypervisor.
  <br>
  I love <a href=https://www.google.com/search?q=cute+kitten&tbm=isch>cats</a>, <a href=https://www.google.com/search?q=pug%7Cbeagle+puppy&tbm=isch>dogs</a>,
  <a href=http://www.guitarpress.com/images/Paganini_Ghiribizzi.pdf>classical guitars</a>, <a href=http://www.ibdof.com/author_books.php?author=68>science</a>
  <a href=http://www.startrek.com/>fiction</a> and <a href=http://xkcd.com/>science-related humour</a>.
  <br><br>
  I recently started working as a software engineer at <a href=http://www.ntop.org/>ntop</a>. If you want to take a deeper look about projects I had fun with, here's my classic-style <a href=http://sn.im/29ia0p7 target="_blank">resume</a>, while if you prefer a more project-oriented description, <a href=http://sn.im/29ia1fe target="_blank">here</a> it is.
  <br>
  If you're stuck on the cats page, I'm sorry, I can't help.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ava.webhop.me" # the base hostname & protocol for your site
twitter_username: AriannaAvanzini
github_username:  ariava
gplus_username: AriannaAvanzini
linkedin_username: AriannaAvanzini
linkedin_profile: arianna-avanzini/4a/461/a8b

# Build settings
markdown: kramdown
